version: '3.8'

services:
  urban-app:
    build: .
    ports:
      - "3080:3080"
    environment:
      - NODE_ENV=production
      - PORT=3080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
